### ISSUE TITLE
HTTP access shutting down June 24th, 2021

### ISSUE THREAD

**Issue by ivanfreeside** [ssimms/business-us-usps-webtools#2]
USPS is sending notices that HTTP access will be turned off shortly, in favor of HTTPS.  It looks like this module connects using HTTP.  I haven't yet tested whether simply changing ->scheme('http') to ->scheme('https') in sub _make_url is all that is needed, or if there's more involved.

It would be great if this could be fixed soon, since we're just about two months from the deadline.  If you need help, let me know and I would be happy to assist (my CPAN ID is IVAN).

**Comment by ivanfreeside** [comment]
s/http/https/ worked for me in the older, LWP-using versions of this module I have in production for customers, so my immediate production deadline/needs are good.  I have not yet tested the new Mojo::UserAgent version.

**Comment by ssimms** [comment]
I apparently don't have notifications set up for this repository, so I didn't see this issue until I was readying a release, sorry.  The good news is that it's fixed and a release will be out shortly.

Changing `http` to `https` is enough for the production environment.  If you're using the testing/staging environment as well, the URL for that endpoint needs to be updated.
